parameters:
  n_estimators: 100  # Número de árvores no RandomForest
  max_depth: 10      # Profundidade máxima da árvore
  random_state: 23   # Semente para reprodutibilidade
  verbose: 0         # Nível de verbosidade do modelo

tracking_uri:
  experiment_name: "pizza-diameter" 